### ISSUE TITLE
Getting client_id and client_secret

### ISSUE THREAD

**Issue by FeedTheChunk** [arfonso01/auto-heroic-categories#1]
Can we get more information on how to register this to obtain a CLIENT_ID & CLIENT_SECRET?  The link just opens up the development portal in Twitch without any guidance.

thanks

**Comment by arfonso01** [comment]
Hello, you need to follow [these steps](https://api-docs.igdb.com/?getting-started#account-creation)
1. Sign Up with [Twitch](https://dev.twitch.tv/login) for a free account
2. Ensure you have Two Factor Authentication [enabled](https://www.twitch.tv/settings/security)
3. Register your application in the [Twitch Developer Portal](https://dev.twitch.tv/console/apps/create)
4. [Manage](https://dev.twitch.tv/console/apps) your newly created application
5. Generate a Client Secret by pressing [New Secret]
6. Take note of the Client ID and Client Secret

If you have any problems during the process, do not hesitate to write here.

**Comment by FeedTheChunk** [comment]
It's the No. 3 that has me confused.  What application our we to register?  I get this is probably stupidly obvious but I'm just not getting it.  Sorry.

**Comment by arfonso01** [comment]
It is a normal step in this type of API.

name: auto_heroic_categories
url: https://localhost:44342/
category: other
confidential
create

If it doesn't let you create it, refresh the page until you get it.

**Comment by FeedTheChunk** [comment]
Thanks for that.  I'll give that a try and report back later if I have issues.  Seems fairly straight forward.
