### ISSUE TITLE
run.sh error messages

### ISSUE THREAD

**Issue by FeedTheChunk** [arfonso01/auto-heroic-categories#2]
./run.sh: line 2: python: command not found
./run.sh: line 3: venv/bin/activate: No such file or directory
./run.sh: line 4: pip: command not found
./run.sh: line 5: python: command not found
./run.sh: line 6: python: command not found
./run.sh: line 7: deactivate: command not found

I installed the prereq's `sudo apt install wget git python3 python3-venv` but the bash script still fails.  Kubuntu 24.04 LTS x86_64.

c

**Comment by FeedTheChunk** [comment]
Fixed by changing python -> python3.

after running it again:

FileNotFoundError: [Errno 2] No such file or directory: '/home/$USER/.var/app/com.heroicgameslauncher.hgl/config/heroic/store/config.json'

I'm completely Python ignorant.  tried to learn it once but got lost very fast.  Looks like the environment variable USER isn't pulling from the environment variable?

Sorry the complete error message is:
`  File "/home/chuck/temp/auto/heroic_categories.py", line 10, in <module>
    custom_categories=open(HEROIC_CONFIG)
                      ^^^^^^^^^^^^^^^^^^^
`

**Comment by FeedTheChunk** [comment]
Never mind.  I found my mistake.  I didn't change $USER in the .env file.

**Comment by arfonso01** [comment]
So, does it already work for you?

**Comment by FeedTheChunk** [comment]
It worked fine once I edited run.sh and correctly edited the paths in the .env file.  I would suggest that maybe the readme needs to be a little more clearer and run.sh should probably be edited so that it explicitly calls phython3 so users who don't have alias python=python3 in the .bashrc file or python-as-python3 installed won't have the same issue.  If I was better with get I'd make a pull request but I just don't feel comfortable making a pull request against some else's repo.
